/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import tarefa.Tarefa;
import tarefaDAO.TarefaDAO;

/**
 *
 * @author muril
 */
public class TelaConsultarById extends javax.swing.JFrame {

    /**
     * Creates new form TelaConsultarById
     */
    public TelaConsultarById() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        VoltarConsultaBtn = new javax.swing.JButton();
        idConsultaLbl = new javax.swing.JLabel();
        idConsultaTxt = new javax.swing.JTextField();
        consultarBtn = new javax.swing.JButton();
        nomeCunsultaLbl = new javax.swing.JLabel();
        nomeConsultaTxt = new javax.swing.JLabel();
        descricaoConsultaLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        descricaoConsultaTxt = new javax.swing.JLabel();
        categoriaConsultaLbl = new javax.swing.JLabel();
        categoriaConsultaTxt = new javax.swing.JLabel();
        responsavelConsultaLbl = new javax.swing.JLabel();
        responsavelConsultaTxt = new javax.swing.JLabel();
        emailResponsavelConsultaLbl = new javax.swing.JLabel();
        emailResponsavelConsultaTxt = new javax.swing.JLabel();
        setorConsultaLbl = new javax.swing.JLabel();
        setorConsultaTxt = new javax.swing.JLabel();
        dataAberturaConsultaLbl = new javax.swing.JLabel();
        dataLimiteConsultaLbl = new javax.swing.JLabel();
        statusConsultaLbl = new javax.swing.JLabel();
        dataAberturaConsultaTxt = new javax.swing.JLabel();
        dataLimiteConsultaTxt = new javax.swing.JLabel();
        statusConsultaTxt = new javax.swing.JLabel();
        mensagemConsultaLbl = new javax.swing.JLabel();
        atualizarCmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        atualizarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel1.setText("CONSULTAR/ATUALIZAR");

        VoltarConsultaBtn.setText("Voltar");
        VoltarConsultaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarConsultaBtnActionPerformed(evt);
            }
        });

        idConsultaLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        idConsultaLbl.setText("ID:");

        consultarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        consultarBtn.setText("Consultar");
        consultarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBtnActionPerformed(evt);
            }
        });

        nomeCunsultaLbl.setText("Nome:");

        nomeConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        nomeConsultaTxt.setText("nome...");

        descricaoConsultaLbl.setText("Descrição:");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setFocusCycleRoot(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 200));

        descricaoConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        descricaoConsultaTxt.setText("descrição...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(descricaoConsultaTxt)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(descricaoConsultaTxt)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        categoriaConsultaLbl.setText("Categoria:");

        categoriaConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        categoriaConsultaTxt.setText("categoria...");

        responsavelConsultaLbl.setText("Responsável:");

        responsavelConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        responsavelConsultaTxt.setText("responsável...");

        emailResponsavelConsultaLbl.setText("Email Responsável:");

        emailResponsavelConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        emailResponsavelConsultaTxt.setText("email responsável...");

        setorConsultaLbl.setText("Setor:");

        setorConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        setorConsultaTxt.setText("setor...");

        dataAberturaConsultaLbl.setText("Data Abertura:");

        dataLimiteConsultaLbl.setText("Data Limite:");

        statusConsultaLbl.setText("Status:");

        dataAberturaConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        dataAberturaConsultaTxt.setText("data abertura...");

        dataLimiteConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        dataLimiteConsultaTxt.setText("data Limite...");

        statusConsultaTxt.setForeground(new java.awt.Color(102, 102, 102));
        statusConsultaTxt.setText("status...");

        mensagemConsultaLbl.setText("Mensagem...");

        atualizarCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Atrasado", "Concluído" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Atualizar Status da Tarefa:");

        atualizarBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        atualizarBtn.setText("Atualizar");
        atualizarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VoltarConsultaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277)
                .addComponent(jLabel1)
                .addContainerGap(368, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(categoriaConsultaLbl)
                    .addComponent(descricaoConsultaLbl)
                    .addComponent(nomeCunsultaLbl)
                    .addComponent(responsavelConsultaLbl)
                    .addComponent(emailResponsavelConsultaLbl)
                    .addComponent(setorConsultaLbl)
                    .addComponent(dataAberturaConsultaLbl)
                    .addComponent(dataLimiteConsultaLbl)
                    .addComponent(statusConsultaLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataAberturaConsultaTxt)
                            .addComponent(dataLimiteConsultaTxt)
                            .addComponent(statusConsultaTxt))
                        .addGap(90, 972, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeConsultaTxt)
                            .addComponent(categoriaConsultaTxt)
                            .addComponent(setorConsultaTxt)
                            .addComponent(emailResponsavelConsultaTxt)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(responsavelConsultaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(idConsultaLbl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idConsultaTxt)
                                    .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(atualizarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mensagemConsultaLbl)
                                .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VoltarConsultaBtn)
                    .addComponent(jLabel1))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeCunsultaLbl)
                            .addComponent(nomeConsultaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoConsultaLbl)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoriaConsultaLbl)
                            .addComponent(categoriaConsultaTxt))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(responsavelConsultaLbl)
                            .addComponent(responsavelConsultaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailResponsavelConsultaLbl)
                            .addComponent(emailResponsavelConsultaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setorConsultaLbl)
                            .addComponent(setorConsultaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataAberturaConsultaLbl)
                            .addComponent(dataAberturaConsultaTxt))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataLimiteConsultaLbl)
                            .addComponent(dataLimiteConsultaTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusConsultaLbl)
                            .addComponent(statusConsultaTxt)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idConsultaLbl)
                            .addComponent(idConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(consultarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(atualizarCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(atualizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(mensagemConsultaLbl)))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void VoltarConsultaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarConsultaBtnActionPerformed
        // TODO add your handling code here:
        try {
            TelaTarefa tt = new TelaTarefa();
            this.dispose();
            tt.setVisible(true);
        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Error" + ex.getMessage());
        }
    }//GEN-LAST:event_VoltarConsultaBtnActionPerformed

    private void consultarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBtnActionPerformed
        // TODO add your handling code here:
        mensagemConsultaLbl.setText("Mensagem...");
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();
        trf.setId(Integer.parseInt(idConsultaTxt.getText()));
        try {
            trf = trfDao.consultarById(trf);
            if (trf.getNomeTarefa() != null) {
                nomeConsultaTxt.setText(trf.getNomeTarefa());
                categoriaConsultaTxt.setText(trf.getCategoria());
                descricaoConsultaTxt.setText(trf.getDescricao());
                responsavelConsultaTxt.setText(trf.getResponsavel());
                emailResponsavelConsultaTxt.setText(trf.getEmailResponsavel());
                setorConsultaTxt.setText(trf.getSetor());
                dataAberturaConsultaTxt.setText(trf.getDataAbertura());
                dataLimiteConsultaTxt.setText(trf.getDataLimite());
                statusConsultaTxt.setText(trf.getStatus());

                mensagemConsultaLbl.setText("Tarefa encontrada!");
            } else {
                mensagemConsultaLbl.setText("Tarefa não encontrada!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            mensagemConsultaLbl.setText("Erro" + ex.getMessage());
        }
    }//GEN-LAST:event_consultarBtnActionPerformed

    private void atualizarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarBtnActionPerformed
        // TODO add your handling code here:
        mensagemConsultaLbl.setText("mensagem...");
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();
        //trf.setId(Integer.parseInt(idConsultaTxt.getText()));

        if (idConsultaTxt.getText().isEmpty()){
            mensagemConsultaLbl.setText("ID não preenchido!");            
        } else {
            try {
                trf.setStatus(String.valueOf(atualizarCmb.getSelectedItem()));
                trf.setId(Integer.parseInt(idConsultaTxt.getText()));                
                trfDao.atualizar(trf);
                mensagemConsultaLbl.setText("Status da tarefa atualizado!");
            } catch (ClassNotFoundException | SQLException ex) {
                mensagemConsultaLbl.setText("ERRO: " + ex.getMessage());
            }
        }
       
    }//GEN-LAST:event_atualizarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultarById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultarById().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VoltarConsultaBtn;
    private javax.swing.JButton atualizarBtn;
    private javax.swing.JComboBox<String> atualizarCmb;
    private javax.swing.JLabel categoriaConsultaLbl;
    private javax.swing.JLabel categoriaConsultaTxt;
    private javax.swing.JButton consultarBtn;
    private javax.swing.JLabel dataAberturaConsultaLbl;
    private javax.swing.JLabel dataAberturaConsultaTxt;
    private javax.swing.JLabel dataLimiteConsultaLbl;
    private javax.swing.JLabel dataLimiteConsultaTxt;
    private javax.swing.JLabel descricaoConsultaLbl;
    private javax.swing.JLabel descricaoConsultaTxt;
    private javax.swing.JLabel emailResponsavelConsultaLbl;
    private javax.swing.JLabel emailResponsavelConsultaTxt;
    private javax.swing.JLabel idConsultaLbl;
    private javax.swing.JTextField idConsultaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mensagemConsultaLbl;
    private javax.swing.JLabel nomeConsultaTxt;
    private javax.swing.JLabel nomeCunsultaLbl;
    private javax.swing.JLabel responsavelConsultaLbl;
    private javax.swing.JLabel responsavelConsultaTxt;
    private javax.swing.JLabel setorConsultaLbl;
    private javax.swing.JLabel setorConsultaTxt;
    private javax.swing.JLabel statusConsultaLbl;
    private javax.swing.JLabel statusConsultaTxt;
    // End of variables declaration//GEN-END:variables
}
