/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import tarefa.Tarefa;
import tarefaDAO.TarefaDAO;

/**
 *
 * @author muril
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeTarefaLbl = new javax.swing.JLabel();
        nomeTarefaTxt = new javax.swing.JTextField();
        descricaoLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        categoriaLbl = new javax.swing.JLabel();
        categoriaCmb = new javax.swing.JComboBox<>();
        responsavelLbl = new javax.swing.JLabel();
        responsavelTxt = new javax.swing.JTextField();
        emailResponsavelLbl = new javax.swing.JLabel();
        emailResponsavelTxt = new javax.swing.JTextField();
        setorLbl = new javax.swing.JLabel();
        setorCmb = new javax.swing.JComboBox<>();
        dataAberturaLbl = new javax.swing.JLabel();
        dataLimiteLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoTxt = new javax.swing.JTextArea();
        statusLbl = new javax.swing.JLabel();
        statusCmb = new javax.swing.JComboBox<>();
        cadastrarBtn = new javax.swing.JButton();
        voltarBtn = new javax.swing.JButton();
        mensagemCadastroLbl = new javax.swing.JLabel();
        dataAberturaTxt = new javax.swing.JFormattedTextField();
        dataLimiteTxt = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        nomeTarefaLbl.setText("Nome Tarefa:");

        descricaoLbl.setText("Descrição:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Tela de Cadastro");

        categoriaLbl.setText("Categoria:");

        categoriaCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta", "Urgente" }));
        categoriaCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaCmbActionPerformed(evt);
            }
        });

        responsavelLbl.setText("Responsável:");

        responsavelTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                responsavelTxtActionPerformed(evt);
            }
        });

        emailResponsavelLbl.setText("Email Responsável:");

        setorLbl.setText("Setor:");

        setorCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Engenharia de Software", "Prototipagem", "Desenvolvimento", "Qualidade", "Recursos Humanos", "Administação", "Comercial" }));

        dataAberturaLbl.setText("Data Abertura:");

        dataLimiteLbl.setText("Data Limite:");

        descricaoTxt.setColumns(20);
        descricaoTxt.setRows(5);
        jScrollPane1.setViewportView(descricaoTxt);

        statusLbl.setText("Status:");

        statusCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Atrasado", "Concluído" }));

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        voltarBtn.setText("Voltar");
        voltarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarBtnActionPerformed(evt);
            }
        });

        mensagemCadastroLbl.setText("Mensagem...");

        try {
            dataAberturaTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dataLimiteTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dataLimiteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataLimiteTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(descricaoLbl)
                                    .addComponent(nomeTarefaLbl))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeTarefaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(categoriaLbl)
                                    .addComponent(responsavelLbl)
                                    .addComponent(emailResponsavelLbl)
                                    .addComponent(setorLbl)
                                    .addComponent(dataAberturaLbl)
                                    .addComponent(dataLimiteLbl)
                                    .addComponent(statusLbl))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(categoriaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(setorCmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(emailResponsavelTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(responsavelTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(dataAberturaTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(dataLimiteTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mensagemCadastroLbl)
                                .addGap(407, 407, 407)
                                .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(voltarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(370, 370, 370)
                        .addComponent(jLabel3)))
                .addContainerGap(437, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltarBtn)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTarefaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nomeTarefaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descricaoLbl)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoriaCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriaLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(responsavelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(responsavelLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailResponsavelLbl)
                            .addComponent(emailResponsavelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(setorLbl)
                            .addComponent(setorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dataAberturaLbl)
                            .addComponent(dataAberturaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(dataLimiteLbl))
                    .addComponent(dataLimiteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statusLbl)
                            .addComponent(statusCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(mensagemCadastroLbl)
                        .addContainerGap(89, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void responsavelTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_responsavelTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_responsavelTxtActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        TarefaDAO trfDao = new TarefaDAO();
        Tarefa trf = new Tarefa();

        if (nomeTarefaTxt.getText().isEmpty() | responsavelTxt.getText().isEmpty() | emailResponsavelTxt.getText().isEmpty()) {
            mensagemCadastroLbl.setText("Preencha todos os campos!");
        } else {
            try {
                trf.setNomeTarefa(nomeTarefaTxt.getText());
                trf.setCategoria(String.valueOf(categoriaCmb.getSelectedItem()));
                trf.setDescricao(descricaoTxt.getText());
                trf.setResponsavel(responsavelTxt.getText());
                trf.setEmailResponsavel(emailResponsavelTxt.getText());
                trf.setSetor(String.valueOf(setorCmb.getSelectedItem()));
                trf.setDataAbertura(dataAberturaTxt.getText());
                trf.setDataLimite(dataLimiteTxt.getText());
                trf.setStatus(String.valueOf(statusCmb.getSelectedItem()));
                trfDao.inserirTarefa(trf);
                mensagemCadastroLbl.setText("Cadastrado com sucesso.");
            } catch (ClassNotFoundException | SQLException ex) {
                mensagemCadastroLbl.setText("ERRO: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    private void categoriaCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaCmbActionPerformed

    private void dataLimiteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataLimiteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataLimiteTxtActionPerformed

    private void voltarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarBtnActionPerformed
        // TODO add your handling code here:
        try {
            TelaTarefa tt = new TelaTarefa();
            this.dispose();
            tt.setVisible(true);

        } catch (SQLException | ClassNotFoundException ex) {
            System.out.println("Error" + ex.getMessage());
        }

    }//GEN-LAST:event_voltarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JComboBox<String> categoriaCmb;
    private javax.swing.JLabel categoriaLbl;
    private javax.swing.JLabel dataAberturaLbl;
    private javax.swing.JFormattedTextField dataAberturaTxt;
    private javax.swing.JLabel dataLimiteLbl;
    private javax.swing.JFormattedTextField dataLimiteTxt;
    private javax.swing.JLabel descricaoLbl;
    private javax.swing.JTextArea descricaoTxt;
    private javax.swing.JLabel emailResponsavelLbl;
    private javax.swing.JTextField emailResponsavelTxt;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensagemCadastroLbl;
    private javax.swing.JLabel nomeTarefaLbl;
    private javax.swing.JTextField nomeTarefaTxt;
    private javax.swing.JLabel responsavelLbl;
    private javax.swing.JTextField responsavelTxt;
    private javax.swing.JComboBox<String> setorCmb;
    private javax.swing.JLabel setorLbl;
    private javax.swing.JComboBox<String> statusCmb;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JButton voltarBtn;
    // End of variables declaration//GEN-END:variables
}
